
# Logging

### GET
GET http://localhost:3002


### GET
GET http://localhost:3002/rider-coordinates


### Create coordinates (success)
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
  "lat": 777.33,
  "lng": 777.44,
  "riderId": "asdf1234_dummy"
}

### Create coordinates (error)
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
  "lng": 233.44,
  "riderId": "asdf1234_dummy"
}
